### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by UsernameKLNU** [diyanqi/GoogleTranslateMakeGrass#1]
>>> mg.makeGrass("苦力怕", 100)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\qxc\GoogleTranslateMakeGrass\mg.py", line 18, in makeGrass
    text=en2cn(cn2en(text))
  File "C:\Users\qxc\GoogleTranslateMakeGrass\mg.py", line 8, in cn2en
    text = translator.translate(source,src='zh-cn',dest='en').text
  File "D:\python3.10.4\lib\site-packages\googletrans\client.py", line 182, in translate
    data = self._translate(text, dest, src, kwargs)
  File "D:\python3.10.4\lib\site-packages\googletrans\client.py", line 78, in _translate
    token = self.token_acquirer.do(text)
  File "D:\python3.10.4\lib\site-packages\googletrans\gtoken.py", line 194, in do
    self._update()
  File "D:\python3.10.4\lib\site-packages\googletrans\gtoken.py", line 62, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by diyanqi** [comment]
遗憾的是，本项目所使用的依赖包已经不再支持。这意味着您无法在本项目上使用谷歌翻译了。非常抱歉。
